language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.9.2
otp_release:
  - 22.1
before_script:
  - export MIX_HOME=$HOME/.mix
  - export MIX_ENV=test
script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix compile --warnings-as-errors --force
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report