language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.6.0
otp_release:
  - 20.2
before_script:
  - export MIX_HOME=$HOME/.mix
  - export MIX_ENV=test
script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix compile --warnings-as-errors --force
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix test
  - mix coveralls.travis