language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.8.1
otp_release:
  - 21.2
before_script:
  - export MIX_HOME=$HOME/.mix
  - export MIX_ENV=test
script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix compile --warnings-as-errors --force
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix test
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report