name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10.3-slim
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        export MIX_ENV=test
        mix local.hex --force
        mix local.rebar --force
        mix deps.get --only test
        mix compile --warnings-as-errors --force

    - name: Run formatter
      run: mix format --check-formatted --dry-run

    - name: Run Credo
      run: mix credo --strict
      env:
        MIX_ENV: "test"

    - name: Run tests
      run: mix test

